name: Webscraping Mensal

on:
  schedule:
    - cron: '0 10 1 * *'
  workflow_dispatch: 

jobs:
  scraping_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar R
        uses: r-lib/actions/setup-r@v2

      - name: Instalar dependências do Sistema (Linux)
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev

      - name: Instalar Pacotes do R
        run: |
          Rscript -e 'install.packages(c("rvest", "dplyr", "stringr", "xml2"), dependencies = TRUE)'

      - name: Rodar script
        run: Rscript ./codigo-r-opf.R

      - name: Salvar resultados
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add ws_opf.csv
          git commit -m "Atualização automática" || echo "Sem alterações"
          git push
